-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgIUwDstjuVH3rYyAz7hLz8LfdAgHKOZhrsqAR8sgmBW+gCgYIKoZIzj0DAQehRANCAAR/npJk0fKfp6OOVes5mznsgTnrcbNRxEtbOcLC8I/CSdQ4K6xi/IIOB0cAP7BZVL1n1Zn7EbGirxYXF8a6Q5h8
-----END PRIVATE KEY-----